# Generated by Django 3.2.19 on 2023-06-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230605_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
